Repository baishan-development-guizhou/golang-library, pull requests merged in 2021-03, with the labels that each got.

#18 feat(changelog): Add generate changelog.
  .chglog/CHANGELOG.tpl.md
  .chglog/config.yml
  go.mod
  go.sum
Labels: Medium, enhancement

#21 #20 log write file config
  log/config.go
Labels: Extra Small

#22 fix(report): fixed fields and tags type.
  report/config.go
  report/global.go
  report/report.go
  report/report_test.go
  report/reporter.go
Labels: Small
